Pull request for the laplist efficiency fix
KDJones2/wifilapper-1 pull request #1
Opened 2016-10-23 14:13 UTC by wonder99

Keith, 
I finally got your repo properly forked, so we can use the official pull-request method now.

2016-10-24 03:50 UTC, KDJones2 approved these changes
First change looks good :)

2016-10-28 02:15 UTC, KDJones2 requested changes
Paul, I really want the CReceiveLap template class back into the code before I merge your changes. I am fine with the other ones.

2016-10-28 02:32 UTC, wonder99 commented
Ok sure

On Oct 27, 2016 10:15 PM, "KDJones2" <notifications@github.com> wrote:

> *@KDJones2* requested changes on this pull request.
>
> Paul, I really want the CReceiveLap template class back into the code
> before I merge your changes. I am fine with the other ones.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/KDJones2/wifilapper-1/pull/1#pullrequestreview-6177956>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFGZu4JjAY962PE2qKHyAhL-zToWNTxpks5q4VrNgaJpZM4KeJJO>
> .
>

2016-11-18 01:29 UTC, KDJones2 approved these changes

2016-11-18 01:30 UTC, merged